### PR TITLE
✅ [migration2viatot2.0]: Migrated SalesForce

### PR DESCRIPTION
**Pull request by burzekj**
## Checklist

This PR:
- [ ] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [x] adds/updates tests (if appropriate)
- [x] adds/updates docstrings (if appropriate)
- [ ] adds an entry in `CHANGELOG.md`

### CODE REVIEW

**Comment by Diego-H-S** [comment]
We are restarting the work on viadot 2 migration. @djagoda881 please, have a look at it!

**Comment by djagoda881** [comment]
@Diego-H-S Please rebase this branch with `2.0` because it has conflicts 
image

**Comment by Diego-H-S** [comment]
I also don't have access, maybe another person should do that. @burzekj assign the PR also to @trymzet.

**Comment by trymzet** [comment]
I'm guessing this can be closed since a duplicate was created https://github.com/dyvenia/viadot/pull/1036

**Pull request closed without merging**
