### PR TITLE
New source C4C

### PR DESCRIPTION
**Pull request by AdamSulek**
## Importance

Added new source to viadot

## Checklist

This PR:
- [x] adds new tests (if appropriate)
- [x]  updates docstrings for any new functions or function arguments (if appropriate)
- [x] updates CHANGELOG.md with a summary of the changes

### CODE REVIEW

**Review by Trymzet — CHANGES_REQUESTED** [review]
- missing `CHANGELOG` entry
- missing tests
- pls remove the `pyodata` dependency as it's not required in your code
- just FYI, the commit history is quite messy, next time pls do a `git rebase` to make it reasonable -- right now only 2 out of 7 commits are related to this PR: 
image

**Comment by AdamSulek** [comment]
- create CHENGLOG entry
- create tests
- removing pyodata from requirements

**Comment by Trymzet** [comment]
@AdamSulek commit names should start with a capital letter and use our naming conventions (start with "Added", "Removed", "Updated", "Fixed", etc.) - the idea is taken from [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by Trymzet** [comment]
Please also use relevant emojis. See other commits by me or @m-paz for reference.

**Pull request closed without merging**
