### PR TITLE
Mindful migration

### PR DESCRIPTION
**Pull request by Diego-H-S**
## Summary
Mindful connector migration from viadot 1 to viadot 2. This connector has also been re-factorized to follow the standardization of connectors. 

Issue link: https://github.com/dyvenia/viadot/issues/733

## Importance
Required by the migration project.

## Checklist

This PR:
- [x] follows the guidelines laid out in `CONTRIBUTING.md`
- [x] links relevant issue(s)
- [x] adds/updates tests (if appropriate)
- [x] adds/updates docstrings (if appropriate)
- [x] adds an entry in `CHANGELOG.md`

### CODE REVIEW

**Comment by Diego-H-S** [comment]
I have to rebase to the new version of the branch. @Rafalz13 @fdelgadodyvenia please wait for it.

It would be necessary a release plan to avoid this kind of situation.

**Comment by Diego-H-S** [comment]
`mindful.py` (source) passed flake8 and pylint:
image

**Comment by Diego-H-S** [comment]
`mindful.py` (task) passed flake8 and pylint:
image

**Comment by Diego-H-S** [comment]
`mindful_to_adls.py` (flow) passed flake8 and pylint:
image

**Comment by Diego-H-S** [comment]
`test_mindful.py` passed flake8 and pylint:
image

Reached minimum goal for testing approval:
image

**Review by fdelgadodyvenia — APPROVED** [review]

**Review by fdelgadodyvenia — APPROVED** [review]

**Pull request merged**
