### PR TITLE
Eurostat migration

### PR DESCRIPTION
**Pull request by adrian-wojcik**
## Summary
Adding modified Eurostat source for Prefect 2.0 with tests

## Importance
Because, it is adding another source to be able to perform on Prefect 2.0

## Checklist

This PR:
- [X] follows the guidelines laid out in `CONTRIBUTING.md`
- [ ] links relevant issue(s)
- [X] adds/updates tests (if appropriate)
- [X] adds/updates docstrings (if appropriate)
- [X] adds an entry in `CHANGELOG.md`

### CODE REVIEW

**Comment by adrian-wojcik** [comment]
Zrzut ekranu 2024-08-29 102511

**Comment by trymzet** [comment]
@adrian-wojcik Please change the base branch to `2.0` (you want to merge the changes into `2.0`).

**Comment by adrian-wojcik** [comment]
@trymzet I was told to create PR to Eurostat_2.0 by @fdelgadodyvenia, which is supposed to be `dev` branch and then Fabio will be merging this branch into 2.0

**Comment by adrian-wojcik** [comment]
Closed in order to recreate without fork

**Pull request closed without merging**
